version: pv00
type: DataPipeline
dataset:
  type: TREC6Corpus
  path:
    train: dataset/trec6/train.txt
    test: dataset/trec6/test.txt
    validation: dataset/trec6/validation.txt
dataloader:
  type: DataLoader
  params:
    num_workers: 4
    batch_size: 256
