type: nsmc
version: v00
optimizer:
  params:
    learning_rate: 1e-3
    scale_factor: 3
scheduler:
  params:
    gamma: 0.95
trainer:
  params:
    max_epochs: 5
    gpus: 2
    distributed_backend: dp
    benchmark: False
    deterministic: True