type: sst2_v0
dataloader:
  params:
    num_workers: 2
    batch_size: 64
optimizer:
  params:
    learning_rate: 3e-4
scheduler:
  params:
    patience: 5
trainer:
  params:
    max_epochs: 10
    gpus: 2
    distributed_backend: "ddp"