type: v0
dataloader:
  params:
    num_workers: 2
    batch_size: 256
optimizer:
  params:
    learning_rate: 1e-3
scheduler:
  params:
    patience: 5
trainer:
  params:
    max_epochs: 5
    gpus: 2
    distributed_backend: "ddp"